routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




 Route::get('list/{category?}','FrontController@home')->name('fronts.list');
Route::get('/hometab','FrontController@hometab');
Route::resource('/','DetailController');
Route::resource('/details','DetailController');
Route::resource('/agents', 'AgentController');
Route::group(['middlewareGroup' => 'webGroup'],function(){
Auth::routes();
// });
// Route::get('/','IndexController@getindex');
// Route::get('/details/test','DetailController@test');
Route::group(['middleware'=>'auth'],function(){
 Route::get('/blank','YieldController@yield');
 

});
});

Route::get('/home', 'HomeController@index')->name('jsontest');

resources/views/partials/_footer.blade.php
<footer class="page-footer">
          <div class="container">
            <div class="row">
              
              <div class="col l3 m3 s12">
                <h5>Company</h5>
                
                    <ul class="left-list">
                      <li><a class="btn-float" href="#!">About Us</a></li>
                      <li><a class="btn-float" href="#!">Contact</a></li>
                      <li><a class="btn-float" href="#!">Blog</a></li>
                      <li><a class="btn-float" href="#!">Advertise</a></li>
                    </ul>
                

               
                    <ul class="left-list">
                      <li><a class="btn-float" href="#!">About Us</a></li>
                      <li><a class="btn-float" href="#!">Contact</a></li>
                      <li><a class="btn-float" href="#!">Blog</a></li>
                      <li><a class="btn-float" href="#!">Advertise</a></li>
                    </ul>
                </div>
             
               <div class="col l3 m3 s12">
                <h5>International Sites</h5>
                <ul>
                  <li><a class="btn-float" href="#!">Sweden</a></li>
                  <li><a class="btn-float" href="#!">USA</a></li>
                  <li><a class="btn-float" href="#!">Israel</a></li>
                  <li><a class="btn-float" href="#!">Singapore</a></li>
                </ul>
              </div>
               <div class="col l3 m3 s12">
                <h5>Join the Newsletter</h5>
                <ul>
                  <p>Get the latest listed property in your email.</p>
                  <input type="email" placeholder="example@example.com" id="email" class="validate"/>
                  <a class="waves-effect waves-light btn" href="#!">Subscribe</a>
                  
                </ul>
              </div>
               <div class="col l3 m3 s12">
                <h5>International Sites</h5>
                <ul>
                   <li><a class="btn-float" href="#!">Sweden</a></li>
                  <li><a class="btn-float" href="#!">USA</a></li>
                  <li><a class="btn-float" href="#!">Israel</a></li>
                  <li><a class="btn-float" href="#!">Singapore</a></li>
                </ul>
              </div>
            </div>
          </div>

          <div class="pattern">
            <img src="Cinqsnipelte/images/pattern.png">
          </div>

          <div class="copyrights">
            <p class="reserve">2016 © Rentma®. All Rights reserved.</p>
            <p class="search">Search & Find All Kinds of Rentals (Home, Apartment,Shop,Land & Rooms/Flat) For Rent.</p>
            <a href="#!"><img src="Cinqsnipelte/images/facebook.png"></a>
                <a href="#!"><img src="Cinqsnipelte/images/twitter.png"></a>
                    <a href="#!"><img src="Cinqsnipelte/images/google+.png"></a>

          </div>
    </footer><!--footer ends-->

resources/views/partials/_nav.blade.php
<nav>
            <div class="container-fluid">
                <div class="nav-wrapper">
                  <a href="/details" class="brand-logo"><img src="../Cinqsnipelte/images/logo1.png"></a>
                  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="fa fa-bars"></i></a>         

                  <ul class="right right-nav ">

                    <div class="hide-on-med-and-down">

                        <li><a href="#"  class="dropdown-button" data-activates="dropdown2">For Tenants <span><i class="fa fa-chevron-down"></i></span></a></li>
                        <li><a href="#"  class="dropdown-button" data-activates="dropdown1">For Landlord <span><i class="fa fa-chevron-down"></i></span></a></li>
                        <li><a href="{{route('agents.index')}} ">Agents</a></li>                    
                        <a href="{{route('details.create')}}" class="waves-effect waves-light btn">
                        Post Now</a>
                    </div>                   
                    <a href="{{ url('/login') }}" class="waves-effect waves-light btn login modal-trigger" data-target="modal1" id="login-btn">Login/Sign Up</a>
                  </ul>

                  <ul class="side-nav menu" id="mobile-demo">
                    <li id="tenants-drop"><a>For Tenants <span><i class="fa fa-chevron-down"></i></span></a></li>
                    <div class="dropdown-tenants active">
                         <li><a href="/list#home">Home</a></li>
                        <li><a href="/list#apartment">Apartment</a></li>
                        <li><a href="/list#flat">Flat/Single Room</a></li>
                        <li><a href="/list#shop">Shop/Shutter</a></li>
                        <li><a href="/list#land">Land</a></li>
                    </div>
                    <li id="landlord-drop"><a>For Landlord <span><i class="fa fa-chevron-down"></i></span></a></li>
                    <div class="dropdown-landlord active">
                        <li><a href="/list#home">Home</a></li>
                        <li><a href="/list#apartment">Apartment</a></li>
                        <li><a href="/list#flat">Flat/Single Room</a></li>
                        <li><a href="/list#shop">Shop/Shutter</a></li>
                        <li><a href="/list#land">Land</a></li>
                    </div>
                    <li><a href="Cinqsnipelte/agents.html">Agents</a></li>  
                    <a href="Cinqsnipelte/post.html" class="waves-effect waves-light btn">Post Now</a>
                   
                  </ul>

                   <div class="user">
                        <a href="#" data-activates="mobile" class="btn-collapse"><img src="Cinqsnipelte/images/card.png" class="circle"><span class="hvr-underline-from-center">Suman Jung</span></a>
                        <ul class="side-nav " id="mobile">
                            <div class="user-logo">                             
                                <img src="Cinqsnipelte/images/card.png" class="circle">
                                <div>
                                    <p>Suman Jung</p>
                                    <a class="btn" id="edit-btn">Edit <i class="fa fa-pencil"></i></a>
                                </div>                      
                            </div>
                            <div class="clearfix"></div>
                            <li class="menu-list">
                                <a class="menu-btn" href="Cinqsnipelte/notification.html" data-hide="true">
                                    <img src="Cinqsnipelte/images/notification-icon.png">
                                    <span class="notifier"></span>
                                    <span class="name">Notifications</span>
                                    <span class="arrow"><i class="fa fa-chevron-right"></i></span>
                                </a>
                            </li>
                            <li class="menu-list">
                                <a class="menu-btn" href="Cinqsnipelte/profile.html" data-hide="false">
                                    <img src="Cinqsnipelte/images/profile-icon.png">
                                    <span class="name">My Profile</span>
                                    <span class="arrow"><i class="fa fa-chevron-right"></i></span>
                                </a>
                            </li>
                            <li class="menu-list">
                                <a class="menu-btn" href=Cinqsnipelte/mypost.html" data-hide="true">
                                    <img src="Cinqsnipelte/images/post-icon.png">
                                    <span class="name">My Posts</span>
                                    <span class="arrow"><i class="fa fa-chevron-right"></i></span>
                                </a>
                            </li>
                            <li class="menu-list">
                                <a class="menu-btn" href="Cinqsnipelte/message.html" data-hide="true">
                                    <img src=Cinqsnipelte/images/message-icon.png">
                                    <span class="notifier"></span>
                                    <span class="name">Messages</span>
                                    <span class="arrow"><i class="fa fa-chevron-right"></i></span>
                                </a>
                            </li>
                             <li class="menu-list">
                                <a class="menu-btn" href="Cinqsnipelte/favourites.html" data-hide="true">
                                    <img src="Cinqsnipelte/images/favourite-icon.png">
                                    <span class="name">Favourites</span>
                                    <span class="arrow"><i class="fa fa-chevron-right"></i></span>
                                </a>
                            </li>
                             <li class="menu-list">
                                <a href="#!" data-hide="none">
                                    <img src="Cinqsnipelte/images/logout-icon.png">
                                    <span class="name">Logout</span>                        
                                </a>
                            </li>
                            <button class="close"><i class="fa fa-chevron-left"></i></button>
                            <div id="content-here"></div>
                        </ul>
                    </div><!--user ends-->

                </div>
            </div>
        </nav>

resources/views/partials/apartmentlist.blade.php
                  

                    @foreach($lists as $a)
                          <div class="card-one col l4 m6 s12">
											<div class="all">
												<a href="{{route('details.show',$a->id)}}" class="main-box">
													
                                 @if(isset(explode('|', $a->images)[0]))
                                  <div class="display-image">
                                    <img src="/image/{{explode('|', $a->images)[0]}}"/><br/>
                                    <span class="caption">{{$a->location}}</span>
                                  </div>
                                @endif
											      	<div class="card-info">					      	
												      	<p class="cost">{{$a->price}} </p>
												      	<p class="need">{{substr($a->description, 0, 30)}}{{strlen($a->description) > 30 ? "..." : "" }}</p>
												      	<div class="icons icon1" >
												      		<div class="belt">
															<button title="Air-conditioned" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/ac.svg">
							    							 	
							    							</button>	
							    							 <button title="Security Camera" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/cc.svg">
							    							 	
							    							 </button>	
							    							 <button title="Electricity" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/electricity.svg">
							    							 	
							    							 </button>	
							    							 <button title="Elevator" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/elevator.svg">
							    							 	
							    							 </button>	
							    							 <button title="Furnished" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/furnished.svg">
							    							 	
							    							 </button>	
							    							 <button title="Garden" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/garden.svg">
							    							 	
							    							 </button>
							    							 <button title="Gym" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/gym.svg">
							    							 	
							    							 </button>	
							    							 <button title="Internet" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/internet.svg">
							    							 	
							    							 </button>	
							    							 <button title="East Faced" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/east.svg">
							    							 	
							    							 </button>	
							    							 <button title="West Faced" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/west.svg">
							    							 	
							    							 </button>	
							    							 <button title="North Faced" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/north.svg">
							    							 	
							    							 </button>	
							    							 <button title="South Faced" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/south.svg">
							    							 	
							    							 </button>	
							    							 <button title="Parking" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/parking.svg">
							    							 	
							    							 </button>	
							    							 <button title="Pets Allowed" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/pets.svg">
							    							 	
							    							 </button>	
							    							 <button title="Swimming Pool" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/pool.svg">
							    							 	
							    							 </button>	
							    							 <button title="Shopping Center" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/shopping.svg">
							    							 	
							    							 </button>	
							    							 <button title="Solar" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/solar.svg">
							    							 	
							    							 </button>	
							    							 <button title="Theatre" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/theatre.svg">
							    							 	
							    							 </button>	
							    							 <button title="Water 24*7" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/water.svg">
							    							 	
							    							 </button>	
							    							 <button title="Power Backup" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/power.svg">
							    							 	
							    							 </button>	
							    							 <button title="Television" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/tv.svg">
							    							 	
							    							 </button>	
															
															</div>
														</div>

												      	<p class="fav"><i class="fa fa-heart"> <span>78 favs</span></i></p>
												      	<p class="view"><i class="fa fa-eye"> <span>1667 views</span></i></p>
												      	<div class="clearfix"></div>						      	
											      	</div>
											    </a>
										      	<a class="btn-floating btn-large waves-effect waves-light fav-btn"><i class="fa fa-heart-o"></i></a>			
									        </div>	
									      </div>
									        @endforeach 
									 
									 

resources/views/partials/belt.blade.php
   
<div class="details-features">      
            <h4>Related <span>Properties</span></h4>
    <div id="carousel-demo1" class="carousel-demo">
            <div class="belt-card">
                <ul class="carousel-wrap">
                @foreach($show as $a)
                    <li class="carousel-wrap-two">                  
                        <div class="all">

                        
                        <a href="{{route('details.show',$a->id)}} " class="main-box">

                                 @if(isset(explode('|', $a->images)[0]))
                                  <div class="display-image">
                                    <img src="/image/{{explode('|', $a->images)[0]}}"/><br/>
                                    <span class="caption">{{$a->location}}</span>
                                  </div>
                                @endif
                                 
                                <div class="card-info">                             
                                    <p class="cost">Rs.{{$a->price}}/mo. </p>
                                    <p class="need">{{substr($a->description, 0, 30)}}{{ strlen($a->description) > 30 ? "..." : ""}} </p>
                                    <div class="icons icon1" >
                                        <div class="belt">
                                        
                                        <button title="Air-conditioned" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/ac.svg">
                                            
                                        </button>   
                                         <button title="Security Camera" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/cc.svg">
                                            
                                         </button>  
                                         <button title="Electricity" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/electricity.svg">
                                            
                                         </button>  
                                         <button title="Elevator" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/elevator.svg">
                                            
                                         </button>  
                                         <button title="Furnished" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/furnished.svg">
                                            
                                         </button>  
                                         <button title="Garden" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/garden.svg">
                                            
                                         </button>
                                         <button title="Gym" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/gym.svg">
                                            
                                         </button>  
                                         <button title="Internet" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/internet.svg">
                                            
                                         </button>  
                                         <button title="East Faced" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/east.svg">
                                            
                                         </button>  
                                         <button title="West Faced" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/west.svg">
                                            
                                         </button>  
                                         <button title="North Faced" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/north.svg">
                                            
                                         </button>  
                                         <button title="South Faced" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/south.svg">
                                            
                                         </button>  
                                         <button title="Parking" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/parking.svg">
                                            
                                         </button>  
                                         <button title="Pets Allowed" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/pets.svg">
                                            
                                         </button>  
                                         <button title="Swimming Pool" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/pool.svg">
                                            
                                         </button>  
                                         <button title="Shopping Center" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/shopping.svg">
                                            
                                         </button>  
                                         <button title="Solar" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/solar.svg">
                                            
                                         </button>  
                                         <button title="Theatre" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/theatre.svg">
                                            
                                         </button>  
                                         <button title="Water 24*7" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/water.svg">
                                            
                                         </button>  
                                         <button title="Power Backup" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/power.svg">
                                            
                                         </button>  
                                         <button title="Television" class="btn-floating waves-effect waves-light">
                                            <img src="../Cinqsnipelte/feature-icons/tv.svg">
                                            
                                         </button>  
                                        
                                        </div>
                                    </div>

                                    <p class="fav"><i class="fa fa-heart"> <span>78 favs</span></i></p>
                                    <p class="view"><i class="fa fa-eye"> <span>1667 views</span></i></p>
                                    <div class="clearfix"></div>                                
                                </div>
                            </a>
                            <a href="#" class="btn-floating btn-large waves-effect waves-light fav-btn"><i class="fa fa-heart-o"></i></a>   
                             @endforeach        
                        </div>                      
                    </li>

                   

resources/views/partials/homelist.blade.php
                           @foreach($lists as $a)
                          <div class="card-one col l4 m6 s12">
											<div class="all">
												<a href="{{route('details.show',$a->id)}}" class="main-box">
													
                                 @if(isset(explode('|', $a->images)[0]))
                                  <div class="display-image">
                                    <img src="/image/{{explode('|', $a->images)[0]}}"/><br/>
                                    <span class="caption">{{$a->location}}</span>
                                  </div>
                                @endif
											      	<div class="card-info">					      	
												      	<p class="cost">{{$a->price}} </p>
												      	<p class="need">{{substr($a->description, 0, 30)}}{{strlen($a->description) > 30 ? "..." : "" }}</p>
												      	<div class="icons icon1" >
												      		<div class="belt">
															<button title="Air-conditioned" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/ac.svg">
							    							 	
							    							</button>	
							    							 <button title="Security Camera" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/cc.svg">
							    							 	
							    							 </button>	
							    							 <button title="Electricity" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/electricity.svg">
							    							 	
							    							 </button>	
							    							 <button title="Elevator" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/elevator.svg">
							    							 	
							    							 </button>	
							    							 <button title="Furnished" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/furnished.svg">
							    							 	
							    							 </button>	
							    							 <button title="Garden" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/garden.svg">
							    							 	
							    							 </button>
							    							 <button title="Gym" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/gym.svg">
							    							 	
							    							 </button>	
							    							 <button title="Internet" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/internet.svg">
							    							 	
							    							 </button>	
							    							 <button title="East Faced" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/east.svg">
							    							 	
							    							 </button>	
							    							 <button title="West Faced" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/west.svg">
							    							 	
							    							 </button>	
							    							 <button title="North Faced" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/north.svg">
							    							 	
							    							 </button>	
							    							 <button title="South Faced" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/south.svg">
							    							 	
							    							 </button>	
							    							 <button title="Parking" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/parking.svg">
							    							 	
							    							 </button>	
							    							 <button title="Pets Allowed" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/pets.svg">
							    							 	
							    							 </button>	
							    							 <button title="Swimming Pool" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/pool.svg">
							    							 	
							    							 </button>	
							    							 <button title="Shopping Center" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/shopping.svg">
							    							 	
							    							 </button>	
							    							 <button title="Solar" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/solar.svg">
							    							 	
							    							 </button>	
							    							 <button title="Theatre" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/theatre.svg">
							    							 	
							    							 </button>	
							    							 <button title="Water 24*7" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/water.svg">
							    							 	
							    							 </button>	
							    							 <button title="Power Backup" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/power.svg">
							    							 	
							    							 </button>	
							    							 <button title="Television" class="btn-floating waves-effect waves-light">
							    							 	<img src="../Cinqsnipelte/feature-icons/tv.svg">
							    							 	
							    							 </button>	
															
															</div>
														</div>

												      	<p class="fav"><i class="fa fa-heart"> <span>78 favs</span></i></p>
												      	<p class="view"><i class="fa fa-eye"> <span>1667 views</span></i></p>
												      	<div class="clearfix"></div>						      	
											      	</div>
											    </a>
										      	<a class="btn-floating btn-large waves-effect waves-light fav-btn"><i class="fa fa-heart-o"></i></a>			
									        </div>	
									      </div>
									        @endforeach 